export {default as Home} from './home/Home'
export {default as Projects} from './projects/Projects'
export {default as Skills} from './skills/Skills'
export {default as students} from './students/Students'
export {default as Contact} from './contact/Contact'
export {default as NotFound} from './notFound/NotFound'
